version: '3'
services:
  controller:
    build:
      context: backend/controller/
      dockerfile: ../../docker/Backend_Dockerfile
      args:
        - projectName=controller
        - releaseOrDebug=release
    ports:
      - "8081:8081"

  map:
    build:
      context: backend/map/
      dockerfile: ../../docker/Backend_Dockerfile
      args:
        - projectName=map
        - releaseOrDebug=release
    ports:
      - "8082:8082"

  reduce:
    build:
      context: backend/reduce/
      dockerfile: ../../docker/Backend_Dockerfile
      args:
        - projectName=reduce
        - releaseOrDebug=release
    ports:
      - "8083:8083"

  web:
    build:
      context: main_site
    ports:
      - "8080:8080"

